name: project_cleaner
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  interact: ^2.2.0
  dart_core_extensions: ^0.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
